jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: EasyDesk/action-dotnet-build@v1
        with:
          # (Optional) Additional arguments for dotnet build.
          build-args: -v normal

          # (Optional) Build configuration, defaults to 'Release'.
          # If the version starts with the 'v' prefix, it will be removed to conform to the requirements of dotnet pack.
          build-configuration: Release

          # (Optional) The path of the project to build; if omitted, the whole solution is built.
          # path: ./<project-name>/
          
          # (Optional) True if warnings should be treated as errors, defaults to false.
          warnings-as-errors: true
on: 
  push:
    branches:
      - main
